/**
 * schemas.js - Database Schema Definitions
 *
 * Chứa cấu trúc schema cho MASTER_DB và USER_DB
 */

const DB_CONFIG = {
  SPREADSHEET_NAME: "MASTER_DB",
  USER_SHEETS_FOLDER_ID: "1dlc7DeSDw19J9_38E8cJvV5hNeopO3oS",
  SHEETS: {
    USERS: {
      name: "Users",
      idPrefix: "USR",
      columns: [
        "userId",
        "username",
        "email",
        "passwordHash",
        "googleId",
        "avatarUrl",
        "role",
        "level",
        "totalXP",
        "mountainStage",
        "mountainProgress",
        "aiLevel",
        "progressSheetId",
        "emailVerified",
        "verificationToken",
        "verificationExpires",
        "createdAt",
        "lastLogin",
        "isActive",
      ],
    },
    TOPICS: {
      name: "Topics",
      idPrefix: "TOP",
      columns: [
        "topicId",
        "title",
        "description",
        "journey",
        "category",
        "orderIndex",
        "totalStages",
        "minAILevel",
        "minAccuracy",
        "createdAt",
      ],
    },
    MCQ_QUESTIONS: {
      name: "MCQ_Questions",
      idPrefix: "MCQ",
      columns: [
        "questionId",
        "topicId",
        "questionText",
        "optionA",
        "optionB",
        "optionC",
        "optionD",
        "correctAnswer",
        "explanation",
        "difficulty",
        "hint",
        "points",
      ],
    },
    MATCHING_PAIRS: {
      name: "Matching_Pairs",
      idPrefix: "MAT",
      columns: [
        "pairId",
        "topicId",
        "leftItem",
        "rightItem",
        "itemType",
        "difficulty",
        "explanation",
        "hints",
        "points",
      ],
    },
    MINI_CHALLENGES: {
      name: "Mini_Challenges",
      idPrefix: "CHL",
      columns: [
        "challengeId",
        "topicId",
        "type",
        "description",
        "contentJSON",
        "correctAnswer",
        "explanation",
        "difficulty",
        "points",
      ],
    },
    ACHIEVEMENTS: {
      name: "Achievements",
      idPrefix: "ACH",
      columns: [
        "achievementId",
        "title",
        "description",
        "conditionJSON",
        "icon",
        "points",
      ],
    },
    LEADERBOARD: {
      name: "Leaderboard",
      idPrefix: "LDB",
      columns: [
        "rank",
        "userId",
        "username",
        "totalXP",
        "mountainStage",
        "aiLevel",
        "lastUpdated",
      ],
    },
    LOGS: {
      name: "Logs",
      idPrefix: "LOG",
      columns: [
        "logId",
        "timestamp",
        "level",
        "category",
        "userId",
        "action",
        "details",
        "ipAddress",
        "sessionId",
      ],
    },
    ERROR_LOGS: {
      name: "Error_Logs",
      idPrefix: "ERR",
      columns: ["timestamp", "step", "error", "userId", "duration", "stack"],
    },
  },
};

const USER_DB_CONFIG = {
  SHEET_NAME_PREFIX: "USER_DB_",
  SHEETS: {
    PROFILE: {
      name: "Profile",
      columns: [
        "userId",
        "username",
        "level",
        "totalXP",
        "aiLevel",
        "mountainStage",
        "currentStreak",
        "bestStreak",
        "totalTimeSpent",
        "joinedAt",
        "lastActive",
      ],
    },
    TOPIC_PROGRESS: {
      name: "Topic_Progress",
      idPrefix: "PRG",
      columns: [
        "progressId",
        "topicId",
        "topicTitle",
        "quizDone",
        "matchingDone",
        "challengeDone",
        "attempts",
        "accuracy",
        "bestScore",
        "xpEarned",
        "aiScore",
        "aiDecision",
        "status",
        "unlockedAt",
        "completedAt",
      ],
    },
    GAME_HISTORY: {
      name: "Game_History",
      idPrefix: "HST",
      columns: [
        "historyId",
        "topicId",
        "gameType",
        "questionId",
        "userAnswer",
        "isCorrect",
        "timeSpent",
        "pointsEarned",
        "hintUsed",
        "playedAt",
      ],
    },
    KNOWLEDGE_NOTEBOOK: {
      name: "Knowledge_Notebook",
      idPrefix: "NOTE",
      columns: [
        "noteId",
        "topicId",
        "questionId",
        "title",
        "content",
        "tags",
        "savedAt",
      ],
    },
    AI_EVALUATIONS: {
      name: "AI_Evaluations",
      idPrefix: "EVAL",
      columns: [
        "evaluationId",
        "topicId",
        "accuracyScore",
        "speedScore",
        "logicScore",
        "consistencyScore",
        "finalScore",
        "estimatedLevel",
        "strengths",
        "weaknesses",
        "recommendNextTopic",
        "evaluatedAt",
      ],
    },
    ACHIEVEMENTS: {
      name: "Achievements",
      idPrefix: "UACH",
      columns: [
        "userAchievementId",
        "achievementId",
        "title",
        "points",
        "unlockedAt",
      ],
    },
    SESSION_LOGS: {
      name: "Session_Logs",
      idPrefix: "SES",
      columns: ["sessionId", "loginAt", "logoutAt", "device", "ipAddress"],
    },
  },
};
