/**
 * schemas.js - Database Schema Definitions
 *
 * Chứa cấu trúc schema cho MASTER_DB và USER_DB
 */

const DB_CONFIG = {
  SPREADSHEET_NAME: "MASTER_DB",
  USER_SHEETS_FOLDER_ID: "1dlc7DeSDw19J9_38E8cJvV5hNeopO3oS",
  SHEETS: {
    USERS: {
      name: "Users",
      idPrefix: "USR",
      columns: [
        "userId",
        "googleId",
        "email",
        "displayName",
        "username",
        "passwordHash",
        "avatarUrl",
        "role",
        "level",
        "aiLevel",
        "totalPoints",
        "totalXP",
        "currentStreak",
        "longestStreak",
        "lastActiveDate",
        "lastLogin",
        "createdAt",
        "isActive",
        "mountainPosition",
        "mountainStage",
        "mountainProgress",
        "totalQuizAnswered",
        "totalPuzzleSolved",
        "totalChallengeCompleted",
        "progressSheetId",
        "emailVerified",
        "verificationToken",
        "verificationExpires",
      ],
    },

    TOPICS: {
      name: "Topics",
      idPrefix: "TOP",
      columns: [
        "topicId",
        "title",
        "description",
        "category",
        "order",
        "iconUrl",
        "estimatedTime",
        "prerequisiteTopics",
        "isLocked",
        "unlockCondition",
        "createdBy",
        "createdAt",
        "updatedAt",
      ],
    },

    MCQ_QUESTIONS: {
      name: "MCQ_Questions",
      idPrefix: "MCQ",
      columns: [
        "questionId",
        "topicId",
        "questionText",
        "optionA",
        "optionB",
        "optionC",
        "optionD",
        "correctAnswer",
        "explanation",
        "difficulty",
        "hint",
        "points",
        "relatedTopics",
        "imageUrl",
        "timeLimit",
        "aiPromptTemplate",
      ],
    },

    CODE_PUZZLES: {
      name: "Code_Puzzles",
      idPrefix: "PUZ",
      columns: [
        "puzzleId",
        "topicId",
        "puzzleType",
        "title",
        "description",
        "codeBlocks",
        "correctOrder",
        "correctAnswer",
        "buggyLine",
        "fixedCode",
        "explanation",
        "difficulty",
        "hints",
        "points",
      ],
    },

    CHALLENGES: {
      name: "Challenges",
      idPrefix: "CHL",
      columns: [
        "challengeId",
        "topicId",
        "title",
        "description",
        "difficulty",
        "unlockCondition",
        "questionList",
        "timeLimit",
        "passingScore",
        "maxAttempts",
        "rewards",
        "story",
      ],
    },

    USER_PROGRESS: {
      name: "User_Progress",
      idPrefix: "PRG",
      columns: [
        "progressId",
        "userId",
        "topicId",
        "quizCompleted",
        "quizCorrect",
        "quizAccuracy",
        "puzzleCompleted",
        "puzzleCorrect",
        "challengeAttempts",
        "challengePassed",
        "topicStatus",
        "currentDifficulty",
        "estimatedLevel",
        "weakPoints",
        "lastQuestionId",
        "lastActivityDate",
        "startedAt",
        "completedAt",
      ],
    },

    ANSWER_HISTORY: {
      name: "Answer_History",
      idPrefix: "ANS",
      columns: [
        "historyId",
        "userId",
        "questionId",
        "questionType",
        "topicId",
        "userAnswer",
        "correctAnswer",
        "isCorrect",
        "timeTaken",
        "pointsEarned",
        "hintUsed",
        "attemptNumber",
        "difficulty",
        "answeredAt",
        "aiExplanation",
        "sessionId",
      ],
    },

    USER_NOTEBOOKS: {
      name: "User_Notebooks",
      idPrefix: "NOTE",
      columns: [
        "noteId",
        "userId",
        "topicId",
        "questionId",
        "title",
        "content",
        "tags",
        "isImportant",
        "createdAt",
        "updatedAt",
        "viewCount",
        "lastViewedAt",
      ],
    },

    ACHIEVEMENTS: {
      name: "Achievements",
      idPrefix: "ACH",
      columns: [
        "achievementId",
        "title",
        "description",
        "iconUrl",
        "category",
        "condition",
        "points",
        "rarity",
      ],
    },

    USER_ACHIEVEMENTS: {
      name: "User_Achievements",
      idPrefix: "UACH",
      columns: [
        "userAchievementId",
        "userId",
        "achievementId",
        "unlockedAt",
        "isViewed",
        "viewedAt",
      ],
    },

    LEADERBOARD: {
      name: "Leaderboard",
      idPrefix: "LDB",
      columns: [
        "rank",
        "userId",
        "displayName",
        "avatarUrl",
        "totalPoints",
        "mountainPosition",
        "level",
        "lastUpdated",
      ],
    },

    AI_EVALUATIONS: {
      name: "AI_Evaluations",
      idPrefix: "EVAL",
      columns: [
        "evaluationId",
        "userId",
        "topicId",
        "evaluationType",
        "accuracyScore",
        "speedScore",
        "consistencyScore",
        "overallScore",
        "estimatedLevel",
        "strengths",
        "weaknesses",
        "recommendations",
        "aiResponse",
      ],
    },

    CHAT_HISTORY: {
      name: "Chat_History",
      idPrefix: "CHAT",
      columns: [
        "chatId",
        "userId",
        "userMessage",
        "aiResponse",
        "context",
        "sentimentScore",
        "isHelpful",
        "createdAt",
      ],
    },

    SYSTEM_LOGS: {
      name: "System_Logs",
      idPrefix: "LOG",
      columns: [
        "logId",
        "timestamp",
        "level",
        "category",
        "userId",
        "action",
        "details",
        "ipAddress",
        "sessionId",
        "errorMessage",
      ],
    },

    ERROR_LOGS: {
      name: "Error_Logs",
      idPrefix: "ERR",
      columns: ["timestamp", "step", "error", "userId", "duration", "stack"],
    },
  },
};

const USER_DB_CONFIG = {
  SHEET_NAME_PREFIX: "USER_DB_",
  SHEETS: {
    PROFILE: {
      name: "Profile",
      columns: [
        "userId",
        "username",
        "level",
        "totalXP",
        "aiLevel",
        "mountainStage",
        "currentStreak",
        "bestStreak",
        "totalTimeSpent",
        "joinedAt",
        "lastActive",
      ],
    },
    TOPIC_PROGRESS: {
      name: "Topic_Progress",
      idPrefix: "PRG",
      columns: [
        "progressId",
        "topicId",
        "topicTitle",
        "quizDone",
        "matchingDone",
        "challengeDone",
        "attempts",
        "accuracy",
        "bestScore",
        "xpEarned",
        "aiScore",
        "aiDecision",
        "status",
        "unlockedAt",
        "completedAt",
      ],
    },
    GAME_HISTORY: {
      name: "Game_History",
      idPrefix: "HST",
      columns: [
        "historyId",
        "topicId",
        "gameType",
        "questionId",
        "userAnswer",
        "isCorrect",
        "timeSpent",
        "pointsEarned",
        "hintUsed",
        "playedAt",
      ],
    },
    KNOWLEDGE_NOTEBOOK: {
      name: "Knowledge_Notebook",
      idPrefix: "NOTE",
      columns: [
        "noteId",
        "topicId",
        "questionId",
        "title",
        "content",
        "tags",
        "savedAt",
      ],
    },
    AI_EVALUATIONS: {
      name: "AI_Evaluations",
      idPrefix: "EVAL",
      columns: [
        "evaluationId",
        "topicId",
        "accuracyScore",
        "speedScore",
        "logicScore",
        "consistencyScore",
        "finalScore",
        "estimatedLevel",
        "strengths",
        "weaknesses",
        "recommendNextTopic",
        "evaluatedAt",
      ],
    },
    ACHIEVEMENTS: {
      name: "Achievements",
      idPrefix: "UACH",
      columns: [
        "userAchievementId",
        "achievementId",
        "title",
        "points",
        "unlockedAt",
      ],
    },
    SESSION_LOGS: {
      name: "Session_Logs",
      idPrefix: "SES",
      columns: ["sessionId", "loginAt", "logoutAt", "device", "ipAddress"],
    },
  },
};
